import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import { ConvexProvider } from "convex/react";
import { ConvexClientProvider } from "../components/convex-client-provider";
import { ThemeProvider } from "../contexts/theme-context";
import { PresenceTracker } from "../components/presence-tracker";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/sign-in">
      <ConvexClientProvider>
        <ThemeProvider>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <PresenceTracker />
              {children}
            </body>
          </html>
        </ThemeProvider>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
